sudo: false
language: node_js
node_js:
  - '4'
  - '0.12'
before_script:
  - 'gem install compass'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script: grunt test
after_success: grunt coveralls
