version: '3'

services:
  #  ################################
  #  #   Setup angular container
  #  ################################
  web:
    build: ./docker
    expose:
      - 9999
    ports:
      - 9999:9999
      - 35729:35729
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run serve

  ################################
  #   Setup nginx load balancer
  ################################
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
      - '443:443'
    #    depends_on:
    #      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs
